[project]
name = "algo-tarakpath"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flask[async]>=3.1.0",
    "flask-cors>=5.0.0",
    "geopandas>=1.0.1",
    "scikit-learn>=1.5.2",
    "aiohttp>=3.11.10",
]
